apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  namespace: mc-stack-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: mc-stack-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: mcstack/minecraft-server
          imagePullPolicy: IfNotPresent
          stdin: true
          tty: true
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: FABRIC
            - name: VERSION
              value: "26.1"
            - name: MODRINTH_PROJECTS
              value: fabric-api
            - name: MEMORY
              value: 2G
            - name: INIT_MEMORY
              value: 1G
            - name: OVERRIDE_SERVER_PROPERTIES
              value: "false"
            - name: SKIP_SERVER_PROPERTIES
              value: "true"
            - name: COPY_CONFIG_DEST
              value: /data
            - name: SYNC_SKIP_NEWER_IN_DESTINATION
              value: "false"
            - name: MOD_GRPC_HOST
              value: "0.0.0.0"
            - name: MOD_GRPC_PORT
              value: "50052"
            - name: API_GRPC_TARGET
              value: "api:50051"
          ports:
            - containerPort: 25565
            - containerPort: 50052
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minecraft-data
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: mc-stack-dev
spec:
  selector:
    app: minecraft
  ports:
    - name: minecraft
      port: 25565
      targetPort: 25565
    - name: grpc
      port: 50052
      targetPort: 50052