name: build-main-mod
on: [pull_request, push]

jobs:
  build-main-mod:
    defaults:
      run:
        shell: bash
        working-directory: ./minecraft/main/mod
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: stage item data
        run: python3 ../stage_item_data.py --root ..
      - name: generate proto sources
        run: ./gradlew generateProto
      - name: run datagen
        run: ./gradlew runDatagen
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            minecraft/main/mod/build/libs/*.jar
            !minecraft/main/mod/build/libs/*-sources.jar
